# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- script: npm install --nosave jquery @aspnet/signalr @aspnet/signalr-protocol-msgpack
  displayName: 'Installing peerDependendies'

- script: npm install
  displayName: 'Installing dependencies'
  
- script: npm run build
  displayName: 'Building the package'

